### PR TITLE
Quick scan camera

### PR DESCRIPTION
**Pull request by KassFlute**
Quick Scan now opens the phone camera and not a qrScan screen.
I can't test scanning a qr code with the emulator.

### CODE REVIEW

**Comment by KassFlute** [comment]
Someone with a real android phone will have to review this pr because the emulator doesn't have the play store (at least for me).

**Comment by KassFlute** [comment]
As discussed during the team onion meeting, we decided to open an external qr scan app for now as not all android phones have a qr code scanner integrated in the default camera app.

Reviewer: Please test on a real android phone with and without the qr scan app. (it is called barcode scanner but it can scan qr codes)

**Review by Valentin889 — CHANGES_REQUESTED** [review]
The codes seems good, on test on my phone I'm corrrectly redirected to Barcode Scanner on the store, however I can't download the app as it's too old, what I suggest is we let the user choose the app they want to use as a scanner as even if I suggest a correct app it might not work on a different phone

**Comment by KassFlute** [comment]
I don't know how to prompt the user to choose an app. Anyways at the end we should implement qr code scanning inside the app and not open an external one.
I replaced the depreciated app with an actual one for now. Can you try again on a real phone?

**Review by Valentin889 — APPROVED** [review]
Seems good for now, good job

**Pull request merged**
