### PR TITLE
Updated Item attributes in database

### PR DESCRIPTION
**Pull request by Mass-14**
added following fields to item.kt, and implied changes in Database.kt and ItemViewModel.kt :
author, visibility, quantity, location

### CODE REVIEW

**Comment by Mass-14** [comment]
@LozanoCyrielle yes as an Int, it will be the index of an Enum (to be created by @Valentin889)

**Comment by LozanoCyrielle** [comment]
If your enum if like enum visibility{no_one, friends, everyont} to call it you will use visibility.friends for example so I don't think it should be an int
we can let it be an int for now and change it after we have the actual enum ig

**Review by LozanoCyrielle — APPROVED** [review]
Except for the enum we maybe will need to change everything is fine

**Review by Patrick-Pataky — APPROVED** [review]
Good enough for me. Visibility and image support still need to be added.

**Comment by Mass-14** [comment]
@Patrick-Pataky in resetDB() what is the purpose of this latch ? Also I don't quite understand how the type Long.toInt would work, does it have an interest to be Long if it then always cast to Int ?
Since these points'll be clear to me, I'll merge :)

**Comment by Patrick-Pataky** [comment]
> @Patrick-Pataky in resetDB() what is the purpose of this latch ? Also I don't quite understand how the type Long.toInt would work, does it have an interest to be Long if it then always cast to Int ? Since these points'll be clear to me, I'll merge :)

- `resetDB()`: The goal of this latch is to block the loading of the app while the stuff in the DB hasn't been deleted. This way, it doesn't fetch the old data. Note that this function would need some additional testing, if it really works well.
- Cast Long to Int: To my understanding, by default numbers in Firestore are *Long*. As our types require *Int*, a cast is needed. Note that another (very logical) solution would be to store data types directly as *Long*. However, I don't think we need such range for our purposes ^^

**Pull request merged**
