### PR TITLE
Fixing Notifications

### PR DESCRIPTION
**Pull request by Patrick-Pataky**
For some reason, some users were able to receive/send notifications, while some others not at all.

This behavior is fixed in this PR.

### CODE REVIEW

**Review by LozanoCyrielle — CHANGES_REQUESTED** [review]
Perfect I have notification now !
The only thing is when I cancel my own loan from the borrow column in inventory I hada notification of my loan what reject

**Review by Mass-14 — CHANGES_REQUESTED** [review]
When I reject an incoming request I have the following message (which isn't right).

image

**Review by Mass-14 — APPROVED** [review]
Tested and it works fine :))

**Review by LozanoCyrielle — APPROVED** [review]
Good ! The notification works and my token isn't null anymore :))

**Pull request merged**
