### PR TITLE
Scan directly in app

### PR DESCRIPTION
**Pull request by Valentin889**
On clic on the wuick scan button now we open directly the camera inside the app which makes the navigation way better because we can stay inside the app for the whole process

### CODE REVIEW

**Comment by LozanoCyrielle** [comment]
Great job ! It had a lot of value to the app.
I found some things to modify :
- the app doesn't ask for camera authorization so I had to go to the settings manually
- the pop up telling us "Qr successfully scanned" pop up several times
- and the camera is over the big button add `Spacer(modifier = Modifier.height(50.dp))` just before your camera call in the if, it will fix this overlap :))

**Comment by Valentin889** [comment]
There is no test for the camera UI that's why I don't have the coverage, however it's not that easy to test and I can't guarentee it will be before the deadline today, if there is no other problem I suggest we merge anyway because it will really help the demo, I can do the test later this week

**Review by LozanoCyrielle — APPROVED** [review]
No more more toast :(
But it works well and add a lot of value to the app. I think we can overlook the lakc of coverage and merge this as it's add a great value to the app

**Comment by LozanoCyrielle** [comment]
After discussing with the team, we agreed on merging without the coverage as the missing coverage is very low, and having this feature for the app is a great value

**Pull request merged**
