### PR TITLE
searchbar implementation

### PR DESCRIPTION
**Pull request by skyrag**

### CODE REVIEW

**Comment by Mass-14** [comment]
Some text fields are outdated with the "Search a task" text, once it will be fixed it seems good to me.

**Comment by KassFlute** [comment]
Search bar shouldn't filter by the id of the items (I think).

**Review by KassFlute — CHANGES_REQUESTED** [review]
not filter on item id

**Comment by skyrag** [comment]
the filter isnt done by the search bar it is a function passed down to the search bar so the mistake came from the function i gave it instead of the function searchbar itself

**Comment by Mass-14** [comment]
UI test result : the blinking line (text cursor) keeps blinking when the keyboard is inactive, to be fixed.

**Review by Mass-14 — APPROVED** [review]
After quick talk in Stand Up Meeting, it has been decided to fix the blinking minor issue later.
TODO later : cancel cursor blinking when keyboard is inactive.

**Pull request merged**
