### PR TITLE
Cl/Update the bottom bar navigation

### PR DESCRIPTION
**Pull request by LozanoCyrielle**
Added the routes and top level destination needed for the bottom bar navigation
We will need to add the actual page when they're coded in the MainActivity

### CODE REVIEW

**Review by Valentin889 — COMMENTED** [review]
The idea make sens but I would move the creation route into the app part, @Patrick-Pataky will do that on the others, the rest of the code seems good

**Comment by Patrick-Pataky** [comment]
I've just refactored App and MainActivity, as described in my last commit. What do you think @LozanoCyrielle @Valentin889 ?

**Review by LozanoCyrielle — COMMENTED** [review]
It seems good to me :)) We can still wait for @Valentin889 triple check but i think this is ready to be merge into main :D

**Review by Patrick-Pataky — APPROVED** [review]
Approved !

**Pull request merged**
