### PR TITLE
Make SonarCloud work

### PR DESCRIPTION
**Pull request by KassFlute**
I try different things to make SonarCloud work

### CODE REVIEW

**Comment by KassFlute** [comment]
The problem :
```
Cannot import coverage information for file 'src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt', coverage data is invalid. Error: {}
java.lang.IllegalStateException: Line 65535 is out of range in the file src/main/java/com/android/partagix/ui/screens/InventoryViewItem.kt (lines: 195)
```

I tried:
- Cleaning the project in the CI before the jacoco task and it then does the following:
"No coverage report can be found with sonar.coverage.jacoco.xmlReportPaths='/home/runner/work/partagix/partagix/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml'. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
Could not report issue with code highlighting, using plain text instead. Check whether the product is outdated."

So the Upload report to SonarCloud can't find the jacoco report

**Comment by zouyonghao** [comment]
I think it will still report the coverage with the IllegalStateException error.
To solve this completely, I suggest you to try following methods:

https://github.com/jacoco/jacoco/issues/1312

https://community.sonarsource.com/t/kotlin-class-coverage-information-fails-importing-due-to-line-65535-is-out-of-range-in-the-file/62522/5

**Comment by KassFlute** [comment]
same problem with jacoco updated to its last version

**Comment by zouyonghao** [comment]
Try to read these documents carefully.

Did you try this configuration?
```kotlin
doLast {
    val reportFile = reports.xml.outputLocation.asFile.get()
    val newContent = reportFile.readText().replace("<line[^>]+nr=\"65535\"[^>]*>".toRegex(), "")
    reportFile.writeText(newContent)

    logger.quiet("Wrote summarized jacoco test coverage report xml to $reportFile.absolutePath}")
}
```

**Comment by KassFlute** [comment]
There isn't the error anymore !! 
I will edit a test file to see if it report correctly the line coverage

**Comment by zouyonghao** [comment]
Good news!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KassFlute** [comment]
need to revert to this commit: 44acc2ac590255546d0551fd79ac2c7dbf8320ac 
and merge this branch to main

**Review by Valentin889 — APPROVED** [review]

**Pull request merged**
