### PR TITLE
Adding the Loan Screen

### PR DESCRIPTION
**Pull request by Patrick-Pataky**
**Added the screen to see the available items to be borrowed in your region !**

Also added support for the Map API key on the CI. 

> :warning: Please add the following files inside the root project folder
- `local.defaults.properties`
- `secrets.properties`
Their content should be a single line with : ```MAPS_API_KEY=XXX``` (the actual key must be asked)

It is not finished in the sense that 2 elements are not implemented:
- One filter consist of adding a calendar, which I haven't managed to do it for now. To be done in a future PR.
- Currently, it is displayed items in the inventory thanks to the InventoryViewModel (currently the whole database). Once a proper ViewModel is created, it needs to be updated.

### CODE REVIEW

**Review by LozanoCyrielle — COMMENTED** [review]
On my phone I don't see any items, i don't know if this is normal
Also when I'm selecting a distance or a quantity, the number is displayed in the search bar

**Review by LozanoCyrielle — COMMENTED** [review]
I think we should display the number we choose from quantity and distance
Also I think the function that filter in term of distance is wrong, because passing from 0km to  10km make items disappear when they shouldn't

**Comment by Valentin889** [comment]
Sounds good to me

**Review by Valentin889 — APPROVED** [review]

**Comment by Patrick-Pataky** [comment]
> Sounds good to me, needs some tests

Will be done in the next PR !

**Pull request merged**
