### PR TITLE
Home screen buttons functionalities 

### PR DESCRIPTION
**Pull request by KassFlute**
I implemented the functionalities of the 3 buttons on the home screen. The "quick scan" button redirect on a sample screen until the real QrScanScreen is implemented.

### CODE REVIEW

**Comment by KassFlute** [comment]
The tests already include clicking on the three buttons

**Review by Valentin889 — CHANGES_REQUESTED** [review]
Seems good in general
There one tiny thing, on the issue #118 it's said that when you go to the inventory you should open the search bar which is not the case at the moment

**Comment by KassFlute** [comment]
> Seems good in general There one tiny thing, on the issue #118 it's said that when you go to the inventory you should open the search bar which is not the case at the moment

I know, I tried to create a new navigation function that allows to navigate to a screen and focus to a specific element but I didn't managed to make it work :/ 
I'll try again for some time

**Comment by KassFlute** [comment]
I spent some hours trying to use a FocusRequester to focus on the search bar from the nav controller. But among the many ways I tried to share a FocusRequester between the different classes none of them has worked.

**Review by Valentin889 — APPROVED** [review]
Seems good, the issue with the search bar is not that big to focus on it at the moment

**Pull request merged**
