### PR TITLE
InventoryViewItem screen tests

### PR DESCRIPTION
**Pull request by KassFlute**

### CODE REVIEW

**Comment by KassFlute** [comment]
I merged the main to have the new SonarCloud analysis on line coverage

**Comment by KassFlute** [comment]
Yeah but I'm still figuring out why SonarCloud is not working :/

**Review by Valentin889 — APPROVED** [review]

**Comment by KassFlute** [comment]
Please don't merge others branches when they don't ask for review. I was trying different things to make SonarCloud work

**Comment by KassFlute** [comment]
98% line coverage according to jacoco

**Pull request merged**
