### PR TITLE
Ab/view account 

### PR DESCRIPTION
**Pull request by AntoineBut**
Basic UI for view account from sprint 2

### CODE REVIEW

**Review by LozanoCyrielle — CHANGES_REQUESTED** [review]
The CI doesn't pass, maybe you didn't format the code before pushing it
Also you don't get the user information for now, you need to do a ViewModel to do so, but the rest seems godd :))

**Comment by AntoineBut** [comment]
Corrected as you said, thank you for the feedback :))

**Comment by Valentin889** [comment]
Seems good to me, maybe add it to the app so we can actually navigate there
```
composable(Route.ACCOUNT) {
        ViewAccount()
      }
```
You'll also need to pass the vm but it can wait until you're done with it

**Review by LozanoCyrielle — CHANGES_REQUESTED** [review]
I saw you pushed here the start of the backend so we will need to review this PR again when u finished the backend

**Pull request closed without merging**
