### PR TITLE
Adding tests for Loan Screen

### PR DESCRIPTION
**Pull request by Patrick-Pataky**
Coverage for Loan Screen should be pretty high (>90%)

### CODE REVIEW

**Comment by Patrick-Pataky** [comment]
Do not merge now. For some reasons, the search bar doesn't work anymore in the Loan Screen, this should be fixed. Also, the permission handling should be a little be smoother

**Comment by Patrick-Pataky** [comment]
Ready to be merged, waiting for a review. The End-To-End test has been commented, as it is independent of this PR and blocks the merge.

**Review by LozanoCyrielle — CHANGES_REQUESTED** [review]
First I think you should leave the TODO in the end to end test because your test doesn't include a user flow so this is something we will need to do
Also when testing our branch the goback button of the search bar doesn't clear the query, it only dismiss the keyboard

**Review by LozanoCyrielle — APPROVED** [review]
Perfect ! Now the search bar works perfectly.
I just fixed the little navigation to the view item issue: Now the navigate to route doesn't take the it of the item, but you need to have the item view model and update the UI state with the item you want to show :))
Other than everything is good, you did a fantastic job on the loan screen

**Pull request merged**
