### PR TITLE
Cl/start or end loan screens

### PR DESCRIPTION
**Pull request by LozanoCyrielle**
I modified the screen into popups.

- Start Loan : Display the item, when clicking on the item, we are redirected to the view item page
                     Start and Cancel Loan buttons : we can start the loan, or cancel it (imagine the item is broken you don't want to 
                     borrow it)

- End Loan : Same thing for the item displayed
                    End Loan button : end the loan

Also added the tests

### CODE REVIEW

**Review by Mass-14 — CHANGES_REQUESTED** [review]
First of all great work, it's way better as a pop-up :)
Here are some points to fix :
1. file testing.kt should be deleted 
2. EndLoanScreen() never uses the modifier in argument, you should use it everywhere across the file (i.e. `modifier` instead of `Modifier`)
3. Same remark for modifier as above in StartLoanScreen()
4. On both Start or End pop-up, clicking outside the pop-up leave me on a blank screen instead of acting like the "close" icon ( X ).
5. On both pop-ups there lack some side paddings (see picture below). (the other paddings are really great tho !)

Capture d'écran 2024-05-16 164117

**Comment by LozanoCyrielle** [comment]
> 2\. EndLoanScreen() never uses the modifier in argument, you should use it everywhere across the file (i.e. `modifier` instead of `Modifier`)

I didn't used it because it made the screen very weird :
image
The only way I managed to make the screen with the correct UI was to use Modifier instead of modifier

**Review by Mass-14 — CHANGES_REQUESTED** [review]
Great fix for clicking out of the pop-up :)
Concerning the `modifier`, I don't see a major issue to avoid it in this screen, however you should then remove it from the screen arguments.
Finally there is still a UI problem with the End loan : the bottom padding in to narrow, which creates an incoherence in the pop-up.
image_2024-05-16_213955376

**Comment by LozanoCyrielle** [comment]
> Great fix for clicking out of the pop-up :) Concerning the `modifier`, I don't see a major issue to avoid it in this screen, however you should then remove it from the screen arguments. Finally there is still a UI problem with the End loan : the bottom padding in to narrow, which creates an incoherence in the pop-up. 

My bad, I didn't pay attention to this, it's fixed now !

**Review by Mass-14 — APPROVED** [review]
Nice job :)

**Pull request merged**
