### PR TITLE
Cl/Call to other acount

### PR DESCRIPTION
**Pull request by LozanoCyrielle**
Add the the corrected navigation and go to the account of other user (home, incoming loan, outcoming loan, and inventory borrowed items)

### CODE REVIEW

**Review by Mass-14 — CHANGES_REQUESTED** [review]
There is a mysterious bug on the last version of your PR : when clicking the home or inventory of the bottom bar, I'm redirected to valentin's or antoine's profile. 
This comes from the last 2 commits, since it was working beforehand.

**Comment by LozanoCyrielle** [comment]
> There is a mysterious bug on the last version of your PR : when clicking the home or inventory of the bottom bar, I'm redirected to valentin's or antoine's profile. This comes from the last 2 commits, since it was working beforehand.

Patrick was able to help me fix this issue, I also fix the navigation to other account of you if you click on you in one of your item (now it goes to your account directly)

**Review by Mass-14 — CHANGES_REQUESTED** [review]
The app crashes when I click on the owner name of a borrowed item of the list, I have the following error : 

```
java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation/OtherAccount/ } cannot be found in the navigation graph NavGraph(0x0) startDestination={Destination(0x78c9ba0c) route=Home}
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:1787)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:2186)
                                                                                                    	at androidx.navigation.NavController.navigate$default(NavController.kt:2181)
                                                                                                    	at androidx.navigation.NavController.navigate(NavController.kt:2166)
                                                                                                    	at com.android.partagix.ui.navigation.NavigationActions.navigateTo(NavigationActions.kt:59)
                                                                                                    	at com.android.partagix.ui.screens.InventoryScreenKt$InventoryScreen$4$2$3$3.invoke(InventoryScreen.kt:237)
                                                                                                    	at com.android.partagix.ui.screens.InventoryScreenKt$InventoryScreen$4$2$3$3.invoke(InventoryScreen.kt:226)
                                                                                                    	at com.android.partagix.ui.components.ItemUiKt$ItemUi$5.invoke(ItemUi.kt:140)
                                                                                                    	at com.android.partagix.ui.components.ItemUiKt$ItemUi$5.invoke(ItemUi.kt:140)```
                                                                                                    	
 We are near to the final result for this task, keep it up !

**Review by Mass-14 — APPROVED** [review]
Great job it works well and code in clean !!

**Pull request merged**
