### PR TITLE
Cl/duplicate loans

### PR DESCRIPTION
**Pull request by LozanoCyrielle**
I fixed the problem where a loan was displayed multiple times on the home, incoming, and outgoing screens.
For now, I also commented on the things related to the number of incoming/outgoing as it's not functional now and is a bigger fix than we think, to have a clean version for the M3 (and it should be the purpose of another PR)
I used multiple manage loan view model, because we had the old loans being displayed before the ones we wanted were being fetched/displayed.

### CODE REVIEW

**Review by AntoineBut — COMMENTED** [review]
The missing coverage is entirely coming from App.kt, which is not covered anymore because we had to delete the EndToEnd test that was making the CI fail randomly (and was not acceptable anymore with 50 minutes CI).
I guess we didn't realize that it would cause this kind of problem.

I might add that the lines that are not tested in App.kt are modified lines and not added. They were already uncovered, so merging this will not change the overall coverage.

For the 5% missing coverage, considering coverage on all other files is 100%, I am inclined to approve this (also because this was a last minute bug fix entirely done on a Sunday afternoon).

However, why did you comment some code ? Is it not used anymore ?

**Comment by LozanoCyrielle** [comment]
> However, why did you comment some code ? Is it not used anymore ?

I commented those because it's related to the number I commented on the inventory screen. This is a small detailes that I couldn't fix in such a short time so I preferred to comment those (so we don't lose any of it) but we can have a clean version for M3

**Comment by AntoineBut** [comment]
> > However, why did you comment some code ? Is it not used anymore ?
> 
> I commented those because it's related to the number I commented on the inventory screen. This is a small detailes that I couldn't fix in such a short time so I preferred to comment those (so we don't lose any of it) but we can have a clean version for M3

Ok I see. Obviously the added value of this bug fix is higher than these 2 UI items. Im adding a task for next sprint to restore those!

Thank you Cyrielle for this last minute PR that greatly improve the product for the milestone.

**Review by AntoineBut — APPROVED** [review]
Thank you for this good work!

**Pull request merged**
