### PR TITLE
Major performance fix

### PR DESCRIPTION
**Pull request by AntoineBut**
Every item in the item list created its own instance of inventoryViewModel, which created major performance issues.

### CODE REVIEW

**Review by LozanoCyrielle — CHANGES_REQUESTED** [review]
It's indeed a lot faster, but if you create or edit an item, the inventory is not updated.
So maybe you can reload the inventory after creating or editing an item

**Review by skyrag — COMMENTED** [review]
the loading seems to be faster and the code makes me think that it should also be faster however I am currently unable to test the fonction concerning the update of the Item because for some reason the create item button doesnt work, also having only one item in the list isnt the best to test the performances

**Comment by AntoineBut** [comment]
Inventory UI is now properly updated on item creation / edit.

**Review by skyrag — APPROVED** [review]
everything works and feels better than before good changes

**Review by LozanoCyrielle — CHANGES_REQUESTED** [review]
I can now create items, but if I want to edit it, it just creates a new item :
If I rename a in ab I now have 2 items: a and ab

**Review by LozanoCyrielle — APPROVED** [review]
I reloaded from the disk and now it works perfectly :))

**Comment by AntoineBut** [comment]
Created the issue on the scrum board as it was missing.

**Pull request merged**
